export const SET_CATEGORY_TYPE = "SET_CATEGORY_TYPE";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODCUTS_SUCCESS = "GET_PRODCUTS_SUCCESS";
export const GET_PRODCUTS_ERROR = "GET_PRODCUTS_ERROR";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const GET_SEARCH_SUGGESTION = "GET_SEARCH_SUGGESTION";
