export const GET_PRODUCTS_ON_CATEGORY = "CATEGORY/GET_PRODUCTS_ON_CATEGORY";
export const SET_PRODUCTS_ON_CATEGORY = "CATEGORY/SET_PRODUCTS_ON_CATEGORY";
export const FETCH_ERROR_PRODCUT_LISTING =
  "CATEGORY/FETCH_ERROR_PRODCUT_LISTING";
export const GET_PRODUCTS_ON_SCROLL = "GET_PRODUCTS_ON_SCROLL";
export const CLEAR_ALL_PRODUCTS_FROM_STORE = "CLEAR_ALL_PRODUCTS_FROM_STORE";
export const SHOW_PRODUCT_LIST_LOADER = "SHOW_PRODUCT_LIST_LOADER";
