export const GET_PRODUCTS_ON_CATEGORY = "CATEGORY/GET_PRODUCTS_ON_CATEGORY";
export const SET_PRODUCTS_ON_CATEGORY = "CATEGORY/SET_PRODUCTS_ON_CATEGORY";
export const FETCH_ERROR_PRODCUT_LISTING =
  "CATEGORY/FETCH_ERROR_PRODCUT_LISTING";
