export const SAVE_ADDRESS = "MANAGE_ADDRESS/SAVE_ADDRESS";
export const SET_ADDRESS = "MANAGE_ADDRESS/SET_ADDRESS";
export const GET_ADDRESS = "MANAGE_ADDRESS/GET_ADDRESS";
export const IS_UPDATING = "MANAGE_ADDRESS/IS_UPDATING";
export const GET_ESTIMATED_DELIVERY_TIME =
  "MANAGE_ADDRESS/GET_ESTIMATED_DELIVERY_TIME";
export const SET_ESTIMATED_DELIVERY_TIME = "MANAGE_ADDRESS/SET_ESTIMATED_DELIVERY_TIME";
