export const apiEndPoints = {
  authenticate: "/api/authenticate",
  loginUser: "/api/loginUser",
  getProducts: "/api/products",
  getCategoryList: "/api/v1/getCategoryList",
  searchProducts: "/api/query/v1/searchProducts",
  searchSuggestions: "/api/query/v1/searchSuggestions",
  saveAddress: "/secure-api/saveAddress",
  getUserAddress: "/secure-api/getUserAddress",
  getPaymentMethods: "/secure-api/v1/getPaymentMethods",
  viewCart: "/secure-api/viewCart",
  removeCartItem: "/secure-api/v1/removeCartItem",
  updateOrder: "/secure-api/viewCart",
  updateProductQuantity: "/secure-api/v1/updateProductQuantity",
  addCartItem: "/secure-api/addCartItem",
};
