export const UPDATE_FETCHING_PRODUCT_ID = 'CART/UPDATE_FETCHING_PRODUCT_ID'
export const REMOVE_ORDER_ITEM = 'CART/REMOVE_ORDER_ITEM';
export const UPDATE_ITEM_QUANTITY = 'CART/UPDATE_ITEM_QUANTITY';
